/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package richpolis.registrosdb.forms;

import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import richpolis.dbs.Criteria;
import richpolis.model.Registros;
import richpolis.model.RegistrosPeer;
import richpolis.objetos.TableModelRegistros;
import richpolis.objetos.IconCellRenderer;

/**
 *
 * @author richpolis
 */
public class FormPrincipal extends javax.swing.JFrame {

    private FormLogin frmLogin;
    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        inicializarTabla();
        alinearDatos();
        setIconTableCellRender();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        cbBuscar = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        btnEditarRegistro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmitemCrearNuevo = new javax.swing.JMenuItem();
        jmItemSalir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registros");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        cbBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "Telefono", "Celular", "Rango" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        tblRegistros.setModel(tmr);
        tblRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrosMouseClicked(evt);
            }
        });
        tblRegistros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblRegistrosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistros);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnEditarRegistro.setText("Editar registro");
        btnEditarRegistro.setEnabled(false);
        btnEditarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRegistroActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jmitemCrearNuevo.setText("Crear nuevo");
        jmitemCrearNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitemCrearNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(jmitemCrearNuevo);

        jmItemSalir.setText("Salir");
        jmItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmItemSalir);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(614, Short.MAX_VALUE)
                    .addComponent(btnEditarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(146, 146, 146)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(428, Short.MAX_VALUE)
                    .addComponent(btnEditarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        frmAgregar = new FormAgregar(this,true);
        frmAgregar.addWindowListener(new WindowAdapter() {
           @Override
           public void windowClosed(WindowEvent e) {
              actualizarTabla();
           }
        });
        frmAgregar.setVisible(true);

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        btnBuscarRegistros();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrosMouseClicked
        // TODO add your handling code here:
        if(this.tblRegistros.getSelectedRow()>0){
            this.btnEditarRegistro.setEnabled(true);
        }
    }//GEN-LAST:event_tblRegistrosMouseClicked

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnBuscarRegistros();
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void jmitemCrearNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitemCrearNuevoActionPerformed
        // TODO add your handling code here:
        this.btnCrearActionPerformed(evt);
    }//GEN-LAST:event_jmitemCrearNuevoActionPerformed

    private void jmItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jmItemSalirActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tblRegistrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblRegistrosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.abrirRegistroSeleccionado();
        }
        
    }//GEN-LAST:event_tblRegistrosKeyPressed

    private void btnEditarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRegistroActionPerformed
        // TODO add your handling code here:
        if(this.tblRegistros.getSelectedRow()>0){
            this.abrirRegistroSeleccionado();
        }
    }//GEN-LAST:event_btnEditarRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPrincipal frmPrincipal = new FormPrincipal();
                frmPrincipal.setLocationRelativeTo(null);
                frmPrincipal.setVisible(true);
            }
        });
    }
    private TableModelRegistros tmr = new TableModelRegistros();
    private FormAgregar frmAgregar;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditarRegistro;
    private javax.swing.JComboBox cbBuscar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JMenuItem jmitemCrearNuevo;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    private void inicializarTabla() {
        tmr.agregarRegistros(new RegistrosPeer().doSelect());
    }
    
    public void actualizarTabla1(){
        int largo = tmr.getRowCount();
        Criteria criteria;
        for(int cont=largo; cont>=0; cont--){
            tmr.removerRegistro(cont);
        }
        criteria = this.getFindCriteria();
        tmr.agregarRegistros(new RegistrosPeer().doSelect(criteria));
    }
    
    public void actualizarTabla(){
        tmr= null;
        this.btnEditarRegistro.setEnabled(false);
        Criteria criteria;
        tmr = new TableModelRegistros();
        criteria = this.getFindCriteria();
        tmr.agregarRegistros(new RegistrosPeer().doSelect(criteria));
        this.tblRegistros.setModel(tmr);
        this.alinearDatos();
        this.setIconTableCellRender();
    }

    private Criteria getFindCriteria() {
        String campo = this.cbBuscar.getSelectedItem().toString().toLowerCase();
        String valor = this.txtBuscar.getText();
        Criteria c = new Criteria();
        c.setTipoQuery(Criteria.eQuerySelect);
        c.setInstruccion("*");
        c.setFrom("registros");
        if(this.txtBuscar.getText().length()>0){
            if(campo.compareTo("rango")==0)
                c.setWhere(campo+"='"+valor+"'");
            else
                c.setWhere(campo+" LIKE '%"+valor+"%'");
        }
        return c;
    }

    private void btnBuscarRegistros() {
        this.actualizarTabla();
    }
    
    private void abrirRegistroSeleccionado(){
        int fila = this.tblRegistros.getSelectedRow();
        frmAgregar = new FormAgregar(this,true,tmr.getRegistroRow(fila));
        frmAgregar.addWindowListener(new WindowAdapter() {
           @Override
           public void windowClosed(WindowEvent e) {
              actualizarTabla();
           }
        });
        frmAgregar.setVisible(true);
    }
    
    private void alinearDatos(){
        DefaultTableCellRenderer modAlinear = new DefaultTableCellRenderer();
        modAlinear.setHorizontalAlignment(SwingConstants.RIGHT);
        this.tblRegistros.getColumnModel().getColumn(3).setCellRenderer(modAlinear);
        this.tblRegistros.getColumnModel().getColumn(4).setCellRenderer(modAlinear);
        this.tblRegistros.getColumnModel().getColumn(5).setCellRenderer(modAlinear);
    }
    
    private void setIconTableCellRender(){
        IconCellRenderer iconCellRender = new IconCellRenderer();
        this.tblRegistros.getColumnModel().getColumn(1).setCellRenderer(iconCellRender);
        this.tblRegistros.setRowHeight(100);
    }
}
